apiVersion: v1
kind: Pod
metadata:
  name: matrix-pod
spec:
  containers:
    - name: matrix-container
      image: paveldrexler/matrix_assignment:test
      volumeMounts:
      - name: matrix-volume
        mountPath: /usr/app/src 
  volumes:
    - name: matrix-volume
      configMap:
        name: assignment-config-file